[package]
name = "rustyline"
version = "0.1.0"
authors = ["Katsu Kawakami <kkawa1570@gmail.com>"]
description = "Rustyline, a readline implementation based on Antirez's Linenoise"
documentation = "http://kkawakam.github.io/rustyline/rustyline"
repository = "https://github.com/kkawakam/rustyline"
readme = "README.md"
keywords = ["readline"]
license = "MIT"

[dependencies]
libc = "~0.1"
nix = "~0.3"
unicode-width = "~0.1"

[dev-dependencies]
tempdir = "~0.3"
